#!/bin/bash
# Create a proper macOS .app bundle for LocalMind
# This allows "Keep in Dock" to persist across sessions

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

APP_NAME="LocalMind"
BUNDLE_ID="com.localmind.app"
APP_DEST="$HOME/Applications/$APP_NAME.app"

echo ""
echo "============================="
echo "  LocalMind App Bundle Creator"
echo "============================="
echo ""

# Step 1: Build release binary
echo -e "${BLUE}[1/4] Building release binary...${NC}"
if ! command -v cargo &> /dev/null; then
    if [ -f "$HOME/.cargo/env" ]; then
        source "$HOME/.cargo/env"
    else
        echo -e "${RED}[ERROR] Rust/Cargo not found. Install from https://rustup.rs${NC}"
        exit 1
    fi
fi

cd "$SCRIPT_DIR/localmind-rs"
cargo build --release
BINARY_PATH="$SCRIPT_DIR/localmind-rs/target/release/localmind-rs"
if [ ! -f "$BINARY_PATH" ]; then
    echo -e "${RED}[ERROR] Build succeeded but binary not found at $BINARY_PATH${NC}"
    exit 1
fi
cd "$SCRIPT_DIR"
echo -e "${GREEN}[OK] Binary built${NC}"
echo ""

# Step 2: Create .app bundle structure
echo -e "${BLUE}[2/4] Creating .app bundle...${NC}"
rm -rf "$APP_DEST"
mkdir -p "$APP_DEST/Contents/MacOS"
mkdir -p "$APP_DEST/Contents/Resources"

# Copy the Rust binary
cp "$BINARY_PATH" "$APP_DEST/Contents/Resources/localmind-rs"

# Convert PNG icon to icns (best effort)
ICON_PNG="$SCRIPT_DIR/localmind-rs/icons/icon.png"
ICNS_DEST="$APP_DEST/Contents/Resources/AppIcon.icns"
if [ -f "$ICON_PNG" ] && command -v sips &> /dev/null && command -v iconutil &> /dev/null; then
    ICONSET_DIR="$(mktemp -d)/AppIcon.iconset"
    mkdir -p "$ICONSET_DIR"
    for size in 16 32 64 128 256 512; do
        sips -z $size $size "$ICON_PNG" --out "$ICONSET_DIR/icon_${size}x${size}.png" > /dev/null 2>&1 || true
        double=$((size * 2))
        sips -z $double $double "$ICON_PNG" --out "$ICONSET_DIR/icon_${size}x${size}@2x.png" > /dev/null 2>&1 || true
    done
    iconutil -c icns "$ICONSET_DIR" -o "$ICNS_DEST" 2>/dev/null || true
fi

# Write Info.plist
cat > "$APP_DEST/Contents/Info.plist" << PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIdentifier</key>
    <string>${BUNDLE_ID}</string>
    <key>CFBundleName</key>
    <string>${APP_NAME}</string>
    <key>CFBundleDisplayName</key>
    <string>${APP_NAME}</string>
    <key>CFBundleExecutable</key>
    <string>${APP_NAME}</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>0.1.0</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>LSMinimumSystemVersion</key>
    <string>11.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSSupportsAutomaticGraphicsSwitching</key>
    <true/>
    <key>LSUIElement</key>
    <false/>
</dict>
</plist>
PLIST_EOF

# Write the launcher script (Contents/MacOS/LocalMind)
# This script starts the embedding server, then runs the Rust binary.
# PROJECT_ROOT is recorded at bundle-creation time.
cat > "$APP_DEST/Contents/MacOS/$APP_NAME" << LAUNCHER_EOF
#!/bin/bash
# LocalMind launcher — generated by create_macos_app.sh
# Project root recorded at creation time:
PROJECT_ROOT="${SCRIPT_DIR}"
BUNDLE_RESOURCES="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")/../Resources" && pwd)"
EMBEDDING_SERVER_PORT="\${EMBEDDING_SERVER_PORT:-8000}"
SERVER_LOG="\$PROJECT_ROOT/embedding-server/embedding_server.log"
SERVER_PID_FILE="/tmp/localmind_embedding_server.pid"
SERVER_PID=""

cleanup() {
    if [ -n "\$SERVER_PID" ] && kill -0 "\$SERVER_PID" 2>/dev/null; then
        kill "\$SERVER_PID" 2>/dev/null || true
        wait "\$SERVER_PID" 2>/dev/null || true
    else
        local port_pid=\$(lsof -ti:\$EMBEDDING_SERVER_PORT 2>/dev/null || true)
        [ -n "\$port_pid" ] && kill "\$port_pid" 2>/dev/null || true
    fi
    rm -f "\$SERVER_PID_FILE"
}
trap cleanup EXIT INT TERM

# Kill any leftover process on the port
PORT_PID=\$(lsof -ti:\$EMBEDDING_SERVER_PORT 2>/dev/null || true)
[ -n "\$PORT_PID" ] && kill "\$PORT_PID" 2>/dev/null && sleep 1

# Locate venv Python
VENV_PYTHON=""
for candidate in ".venv/bin/python" ".venv/Scripts/python.exe" ".venv/Scripts/python"; do
    full="\$PROJECT_ROOT/embedding-server/\$candidate"
    if [ -f "\$full" ]; then
        VENV_PYTHON="\$full"
        break
    fi
done

if [ -z "\$VENV_PYTHON" ]; then
    osascript -e 'display alert "LocalMind" message "Python virtual environment not found.\n\nRun start_localmind.sh once to set up dependencies, then re-run this app." as critical'
    exit 1
fi

# Start embedding server
export EMBEDDING_SERVER_PORT
rm -f "\$SERVER_LOG"
"\$VENV_PYTHON" "\$PROJECT_ROOT/embedding-server/embedding_server.py" > "\$SERVER_LOG" 2>&1 &
SERVER_PID=\$!
echo \$SERVER_PID > "\$SERVER_PID_FILE"

# Wait for server ready (up to 3 minutes)
MAX_ATTEMPTS=180
ATTEMPT=0
while [ \$ATTEMPT -lt \$MAX_ATTEMPTS ]; do
    ATTEMPT=\$((ATTEMPT + 1))
    if ! kill -0 "\$SERVER_PID" 2>/dev/null; then
        osascript -e "display alert \"LocalMind\" message \"Embedding server crashed on startup.\n\nCheck log: \$SERVER_LOG\" as critical"
        exit 1
    fi
    HEALTH=\$(curl -s "http://localhost:\$EMBEDDING_SERVER_PORT/health" 2>/dev/null || true)
    if echo "\$HEALTH" | grep -q '"model_loaded":.*true'; then
        break
    fi
    if [ \$ATTEMPT -eq \$MAX_ATTEMPTS ]; then
        osascript -e "display alert \"LocalMind\" message \"Embedding server did not become ready in time.\n\nCheck log: \$SERVER_LOG\" as critical"
        exit 1
    fi
    sleep 1
done

# Run the Rust binary
exec "\$BUNDLE_RESOURCES/localmind-rs"
LAUNCHER_EOF

chmod +x "$APP_DEST/Contents/MacOS/$APP_NAME"
echo -e "${GREEN}[OK] Bundle created at: $APP_DEST${NC}"
echo ""

# Step 3: Sign the bundle (ad-hoc) so macOS Gatekeeper doesn't block it
echo -e "${BLUE}[3/4] Signing bundle (ad-hoc)...${NC}"
if command -v codesign &> /dev/null; then
    codesign --force --deep --sign - "$APP_DEST" 2>/dev/null && \
        echo -e "${GREEN}[OK] Signed${NC}" || \
        echo -e "${YELLOW}[WARNING] Ad-hoc signing failed (app may still work)${NC}"
else
    echo -e "${YELLOW}[WARNING] codesign not found, skipping${NC}"
fi
echo ""

# Step 4: Tell Dock / Launch Services about the new bundle
echo -e "${BLUE}[4/4] Registering with Launch Services...${NC}"
if command -v /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister &> /dev/null; then
    /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
        -f "$APP_DEST" 2>/dev/null || true
fi
# Touch the bundle so Finder notices it
touch "$APP_DEST"
echo -e "${GREEN}[OK] Registered${NC}"
echo ""

echo -e "${CYAN}============================${NC}"
echo -e "${CYAN}  Done!${NC}"
echo -e "${CYAN}============================${NC}"
echo ""
echo -e "${GREEN}LocalMind.app installed to:${NC}"
echo "  $APP_DEST"
echo ""
echo -e "${YELLOW}To add to Dock:${NC}"
echo "  1. Open Finder > Go > Home > Applications"
echo "  2. Drag LocalMind.app to your Dock"
echo "  3. Right-click the Dock icon > Options > Keep in Dock"
echo ""
echo -e "${YELLOW}Note:${NC} Run start_localmind.sh at least once first to set up"
echo "  the Python virtual environment and download the embedding model."
echo ""
echo -e "${YELLOW}To update after code changes:${NC}"
echo "  Re-run ./create_macos_app.sh"
echo ""
