[project]
name = "localmind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faiss-cpu>=1.11.0",
    "numpy>=2.3.1",
    "pytest>=8.4.1",
    "requests>=2.32.4",
]
